# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev2_tutorial',
                'doc_host': 'https://FloLangenfeld.github.io',
                'git_url': 'https://github.com/FloLangenfeld/nbdev2_tutorial',
                'lib_path': 'nbdev2_tutorial'},
  'syms': {'nbdev2_tutorial.core': {'nbdev2_tutorial.core.foo': ('core.html#foo', 'nbdev2_tutorial/core.py')}}}