# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev2_tutorial',
                'doc_host': 'https://FloLangenfeld.github.io',
                'git_url': 'https://github.com/FloLangenfeld/nbdev2_tutorial',
                'lib_path': 'nbdev2_tutorial'},
  'syms': { 'nbdev2_tutorial.core': {'nbdev2_tutorial.core.foo': ('core.html#foo', 'nbdev2_tutorial/core.py')},
            'nbdev2_tutorial.main_package': { 'nbdev2_tutorial.main_package.HelloSayer': ( 'main_package.html#hellosayer',
                                                                                           'nbdev2_tutorial/main_package.py'),
                                              'nbdev2_tutorial.main_package.HelloSayer.__init__': ( 'main_package.html#hellosayer.__init__',
                                                                                                    'nbdev2_tutorial/main_package.py'),
                                              'nbdev2_tutorial.main_package.HelloSayer.say': ( 'main_package.html#hellosayer.say',
                                                                                               'nbdev2_tutorial/main_package.py'),
                                              'nbdev2_tutorial.main_package.say_hello': ( 'main_package.html#say_hello',
                                                                                          'nbdev2_tutorial/main_package.py')}}}